[package]
name = "obsidian-vocab-sync"
version = "1.0.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
reqwest = { version = "0.12.24", features = ["json"] }
serde = "1.0.228"
tokio = { version = "1.48.0", features = ["full"] }
tokio-macros = { version = "~2.6.0" }
